### PR TITLE
Fix meili:create when the configuration has no settings

### LINKED ISSUE #176: Command meili:create doesn't create index without settings
**Description**
Running php bin/console meili:create - didnt create index when no settings is present in configuration aka:

```
    indices:
        - name: shopping_gallery_tenant
          class: App\Entity\ShoppingGalleryTenant
          enable_serializer_groups:  true
```

**Expected behavior**
Index is created when no settings is present

**Current behavior**
Index is not created

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: v:0.23.1
- meilisearch-symfony version: v0.7.2

### PR DESCRIPTION
**Pull request by brunoocasali**
Fixes #176

### CODE REVIEW

File: src/Command/MeiliSearchCreateCommand.php [hunk 1]
```diff
@@ -72,7 +72,9 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
             $output->writeln('<info>Creating index '.$index['name'].' for '.$entityClassName.'</info>');
 
-            $indexInstance = $this->searchClient->index($index['name']);
+            $task = $this->searchClient->createIndex($index['name']);
+            $this->searchClient->waitForTask($task['uid']);
+            $indexInstance = $this->searchClient->getIndex($index['name']);
```
Comment (curquiza) [inline src/Command/MeiliSearchCreateCommand.php:77]:
```suggestion
            $indexInstance = $this->searchClient->index($index['name']);
```

Comment (curquiza) [reply src/Command/MeiliSearchCreateCommand.php:77]: If I'm correct, since the index is created, no need to get (using HTTP call), only an instance needs to be created.

Comment (brunoocasali) [reply src/Command/MeiliSearchCreateCommand.php]: Good catch! I thought it could break by just creating the instance from a valid/real index in meili, but there is no need to be worried since no internal data is used to track that, so good catch, your suggestion was applied! ;)

**Review by curquiza — APPROVED** [review]

**Comment by brunoocasali** [comment]
bors merge
