### PR TITLE
Fix deprecations

### LINKED ISSUE #258: Deprecations needs to be fixed
CI outlined these:
```
Remaining indirect deprecation notices (7)

  1x: Using XML mapping driver with XSD validation disabled is deprecated and will not be supported in Doctrine ORM 3.0. (XmlDriver.php:65 called by SimplifiedXmlDriver.php:23, https://github.com/doctrine/orm/pull/6728, package doctrine/orm)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without setting second argument $numberAware=true is deprecated and will be removed in Doctrine ORM 3.0. (UnderscoreNamingStrategy.php:48 called by getDoctrine_Orm_DefaultConfigurationService.php:33, https://github.com/doctrine/orm/pull/7908, package doctrine/orm)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: Doctrine\DBAL\Platforms\AbstractPlatform::usesSequenceEmulatedIdentityColumns is deprecated. (AbstractPlatform.php:3949 called by ClassMetadataFactory.php:626, https://github.com/doctrine/dbal/pull/5513, package doctrine/dbal)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: Column::setCustomSchemaOptions() is deprecated. Use setPlatformOptions() instead. (Column.php:424 called by Column.php:92, https://github.com/doctrine/dbal/pull/5476, package doctrine/dbal)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: SqlitePlatform::canEmulateSchemas() is deprecated. (SqlitePlatform.php:901 called by SchemaTool.php:409, https://github.com/doctrine/dbal/pull/4805, package doctrine/dbal)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: Doctrine\DBAL\Schema\Table::getPrimaryKeyColumns is deprecated. Use getPrimaryKey() and Index::getColumns() instead. (Table.php:820 called by Table.php:708, https://github.com/doctrine/dbal/pull/5731, package doctrine/dbal)
    1x in AggregatorTest::setUp from Meilisearch\Bundle\Tests\Integration

  1x: The Doctrine\ORM\Event\LifecycleEventArgs class is deprecated and will be removed in ORM 3.0. Use Doctrine\Persistence\Event\LifecycleEventArgs instead. (LifecycleEventArgs.php:29 called by DoctrineEventSubscriberTest.php:36, https://github.com/doctrine/orm/issues/9875, package doctrine/orm)
    1x in DoctrineEventSubscriberTest::testPostPersist from Meilisearch\Bundle\Tests\Integration\EventListener
```

### PR DESCRIPTION
**Pull request by norkunas**
# Pull Request

## Related issue
Fixes #258

## What does this PR do?
- Fixes deprecations

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

File: tests/baseline-ignore
Comment (brunoocasali) [inline tests/baseline-ignore:1]: As the stack expert here, you probably had reasons for skipping those warnings here, and I will agree with them. But I would like to have a process or at least know how to avoid those additions. Because to me, this kind of file only grows indefinitely.

**Review by brunoocasali — APPROVED** [review]

File: src/EventListener/DoctrineEventSubscriber.php [hunk 1]
```diff
@@ -4,24 +4,16 @@
 
 namespace Meilisearch\Bundle\EventListener;
 
-use Doctrine\Common\EventSubscriber;
 use Doctrine\Persistence\Event\LifecycleEventArgs;
 use Meilisearch\Bundle\SearchService;
 
-final class DoctrineEventSubscriber implements EventSubscriber
```
[the remark this answers is not in the document]
Comment (norkunas) [reply src/EventListener/DoctrineEventSubscriber.php:11]: Yes, doctrine has listeners and in Symfony it's enough to tag the class with the appropriate event

File: tests/baseline-ignore
Comment (norkunas) [reply tests/baseline-ignore:1]: No, it will be reduced later. There are some indirect deprecations that cannot be fixed and need to wait upstream fix

**Comment by brunoocasali** [comment]
bors merge
