### PR TITLE
Fix(serializer): Properly normalize `DateTimeInterface` objects

### LINKED ISSUE #304: DateTime objects are serialized as strings
Currently, datetime objects are serialized as strings, i.e. `2023-11-29T00:00:00+00:00`. 
This prevents date fields from being filterable (by range).
Aren't they supposed to be serialized as unix timestamp (integers)?

As a workaround I did this:

```php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;

class MyEntity {
    // ...
    
    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    #[Serializer\Context([DateTimeNormalizer::FORMAT_KEY => 'U'])]
    public ?DateTimeImmutable $releasedAt = null;
}
```

It works, except timestamps are rendered as strings, not integers.
To fix this, I created a custom DateTime normalizer:

```php
use DateTimeInterface;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final readonly class UnixTimestampNormalizer implements NormalizerInterface
{
    public function __construct(
        private DateTimeNormalizer $normalizer = new DateTimeNormalizer(),
    ) {
    }

    public function normalize(mixed $object, string $format = null, array $context = []): int
    {
        return (int) $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization(mixed $data, string $format = null, array $context = []): bool
    {
        return $data instanceof DateTimeInterface
            && 'U' === ($context[DateTimeNormalizer::FORMAT_KEY] ?? null);
    }
}
```

But this is a little tricky, it would be better if proper serializing could be done out of the box.

### PR DESCRIPTION
**Pull request by bpolaszek**
# Pull Request

## Related issue
Fixes #304 

## What does this PR do?
- `DateTimeInterface` objects are now normalized as unix timestamps integers, in the context of a serialization initiated by this bundle.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bpolaszek** [comment]
FYI, I could not run PHPUnit on my side - waiting for #308 to be merged

File: src/Services/UnixTimestampNormalizer.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
+
+final class UnixTimestampNormalizer implements NormalizerInterface
+{
+    /**
+     * @param \DateTimeInterface $object
+     */
+    public function normalize(mixed $object, string $format = null, array $context = []): int
+    {
+        return (int) $object->format('U');
```
Comment (norkunas) [inline src/Services/UnixTimestampNormalizer.php:16]:
```suggestion
        return $object->format('U')->getTimestamp();
```
?

Comment (bpolaszek) [reply src/Services/UnixTimestampNormalizer.php]: `$object->getTimestamp()` precisely :-) (didn't even know that method existed!)

Comment (norkunas) [reply src/Services/UnixTimestampNormalizer.php]: yeah, made a typo :D

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
Not sure how we should tackle compat with 5.4

**Comment by bpolaszek** [comment]
> Not sure how we should tackle compat with 5.4

5.4?? what 5.4?

**Comment by bpolaszek** [comment]
> Not sure how we should tackle compat with 5.4

I think the `mixed` keyword should be avoided, let me give it a try

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
bors merge

**Comment by norkunas** [comment]
bors ping

**Comment by norkunas** [comment]
bors try

**Comment by norkunas** [comment]
bors try

**Comment by norkunas** [comment]
Thank you @bpolaszek
